import type { Metadata } from "next";
import { Inter, Mulish } from "next/font/google";
import "./globals.css";
import mongoose from "mongoose";

const inter = Mulish({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // await mongoose.connect(process.env.NEXT_PUBLIC_MONGO_URI!)
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
